name: Ouverture du restaurant
on:
  push:
    branches:
      - main
jobs:
  open-restaurant:
    runs-on: ubuntu-latest
    steps:
      - name: resaurant ouvert
        run: echo "restaurant ouvert"
