name: additions

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dépendances
        run: npm install
      - name: tests
        run: npm test
